version: '2.4'

services:
  express:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/node/app #La cartella node_module del container sara in /node
      - /node/app/node_modules #Maschera (nasconde) il bind_mount di node_modules dall'host
    environment:
      - DEBUG=sample-express:*

