version: '2.4'

services:

  frontend:
    image: nginx
    depends_on:
      api:
        # this requires a compose file version => 2.3 and < 3.0
        condition: service_healthy #richiede che l'health check sia superato
        
  api:
    image: node:alpine
    healthcheck:
      test: curl -f http://127.0.0.1 #definisce il test per l'healthcheck
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1  #definisce il test per l'healthcheck

  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet  #definisce il test per l'healthcheck

  mysql:
    image: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1  #definisce il test per l'healthcheck
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
